### ISSUE TITLE
How to properly destroy taggle instance?

### ISSUE THREAD

**Issue by caracal7** [okcoker/taggle.js#102]

**Comment by okcoker** [comment]
This is sort of a running question. What exactly do you mean destroy? 

You should be able to grab the container and just remove it from the DOM like so:

```js
var container = document.getElementById('taggle-container');

container.parentNode.removeChild(container);
```

**Comment by caracal7** [comment]
Thank you for the quick reply!
I create and destroy at runtime a lot of forms with tags fields. And many other components has constructor and destructor for release memory, event handlers and etc. 
If remove taggle container is enough - its ok)

**Comment by okcoker** [comment]
Yes, the memory be garbage collected as long as you have no other references to the Taggle container or its children DOM nodes after destroying
