### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by caracal7** [okcoker/taggle.js#103]
I think it is more useful if events is fired only if you don't add and remove programatically.

**Comment by okcoker** [comment]
I'm not sure I understand the question. You don't have to use any of the events if you don't want to

**Comment by okcoker** [comment]
Oh I see. In the `onTagAdd` callback, you can check for [the event](https://github.com/okcoker/taggle.js/blob/b8eec0264b8e2fee7821bc3fde8105ac74754b72/src/taggle.js#L864) to determine if it was from the user right?

So something like:

```js
new Taggle(container, {
    onTagAdd: function(e, text) {
        if (e === null) {
            // Programmatically added
        }
        else {
            // Added by user
        }
    }
})

```

**Comment by caracal7** [comment]
Exactly)
