### ISSUE TITLE
Destroy taggle instance

### ISSUE THREAD

**Issue by Mottie** [okcoker/taggle.js#104]
Nice work on this project! Please add a method to destroy an instance of taggle.

**Comment by okcoker** [comment]
Thanks @Mottie. What do you mean destroy?

There are some related issues #65 #27 #102

**Comment by Mottie** [comment]
I don't want to remove the container, just the event listeners when the container isn't focused. Basically freeing up memory when the container isn't being used.

**Comment by Mottie** [comment]
It'd be awesome if I could destroy taggle, leaving the tags, then later reinitialize it on the same tags without having to set the `tags` option.

**Comment by okcoker** [comment]
@Mottie you can use the `removeEvents` and `attachEvents` methods in version 1.13.0.
