### ISSUE TITLE
CSS includes demo styles.

### ISSUE THREAD

**Issue by webdistortion** [okcoker/taggle.js#105]
From what I can see there are some CSS styles in taggle.css that have nothing to do with the component and everything to do with the demo project?  Including these styles blindly will cause conflicts with existing body styles etc. 

Wondering if / should these be removed?

**Comment by okcoker** [comment]
Hmm that's valid if people are copying and pasting. I think i'd rather separate the files into 2. But also there is a minimal style'd link in the readme if that's more of what you're looking for?
 https://jsfiddle.net/okcoker/aqnspdtr/8/

**Comment by Ollie-Saer-WBS** [comment]
Hi there,

This is still a problem.  I've tried to install your library but can't without including the demo stylesheet, which contains a bunch of styles specific to your demo project.

In [other Issue Threads](https://github.com/okcoker/taggle.js/issues/7), you've said that people can just take the styles they want and form their own stylesheet.  Personally, I think this is a bit of a strawman argument, as unless people are willing to trawl through your JS source code, they're not going to know which styles are related to the library itself and which are part of your demo site.

Case and point, I've spent a while trying to extract the relevant styles to a separate stylesheet, and have managed to get _some_ of the appearance working.  However, the bouncing animations still don't work.

Could you please let me know which styles are required just for the library to appear correctly?  I'll probably make a separate stylesheet and later create a pull request for you to put it into the master branch.

This is a really nice looking library, but things like the strange arrangement you've got going with the stylesheet is letting it down.

**Comment by okcoker** [comment]
> This is still a problem. I've tried to install your library but can't without including the demo stylesheet, which contains a bunch of styles specific to your demo project.

> unless people are willing to trawl through your JS source code, they're not going to know which styles are related to the library itself and which are part of your demo site

Did you see https://jsfiddle.net/okcoker/aqnspdtr/8/ linked above? It contains only CSS related to the lib.

The other thread you linked to is why that JS Fiddle was created. After replying to @webdistortion above, no response was given so I can only assume the issue was solved by the fiddle link. 

Maybe the README needs to be updated to make this clearer?

**Comment by Ollie-Saer-WBS** [comment]
Yes, I did take a look at that and managed to get it to work in the end.  Like I said, it's a really nice library and you should be proud of what you've done.

However, I think even putting it in the README is a really roundabout way to do it.  I understand, from reading other Issue threads, that your philosophy with this library is to allow as great a level of customisation as possible, and that's awesome.

However, a lot of people will probably just want to plug this into their site with styles that work and use it as-is.  Others (and I include myself in this camp) will at least want to see it working in its most basic form on their site before investing the time into properly integrating it, as this uses valuable development capital which many professionals simply can't spare on tinkering.

I think your best bet would really be to add these basic styles to the src folder, with a big note in the README regarding the ease at which this library can be customised to suit individual needs aesthetically.

**Comment by okcoker** [comment]
@Ollie-Saer-WBS thanks for your feedback. The minimal CSS is now included
