### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mikias10** [okcoker/taggle.js#106]
https://github.com/okcoker/taggle.js/blob/ce545d994da5501ef9b8c03e5942ecb9053f90bf/src/taggle.js#L352

Getting a `TypeError: Cannot read property 'length' of undefined`. 

Can you add a check for tags?

`if (this.settings.tags && isArray(this.settings.tags) &&  this.settings.tags.length) {} `

**Comment by okcoker** [comment]
Is there a reason `tags` is `undefined` for you?

**Comment by mikias10** [comment]
If the user forgets to pass a default value into your library (tabs || []), the TypeError is bound to get thrown. That's what happened in my case.

**Comment by okcoker** [comment]
Hmm, I think I'd rather have the error thrown in this case. Adding a check to see if `this.settings.tags` is an array will swallow the real root of the problem and could cover up unexpected results. 

I think it's better if the consumer always makes they are passing an array for this option as noted in the docs.

But also it's worth noting in the next major version, there will [be a check](https://github.com/okcoker/taggle.js/blob/ce545d994da5501ef9b8c03e5942ecb9053f90bf/src/taggle.js#L277-L282) to make sure the right options are passed (to prevent typos). We could extend this to make sure the options passed are also of the right _type_ which would alert you of something like `tags: undefined` sooner.

**Comment by mikias10** [comment]
Thanks
