### ISSUE TITLE
Select Input Element

### ISSUE THREAD

**Issue by barrychapman** [okcoker/taggle.js#108]
Is it possible to apply this to a multiple select input with a list of options selected?

We have a tool that generates those automatically, and it would make things much easier

**Comment by okcoker** [comment]
I'm not sure what you mean. Do you mean when an option gets selected within the multiple select input, a tag is added to a text box?

If possible can you provide an example within jsfiddle?

**Comment by MichaelJJames** [comment]
I did this using onTagRemove and on onTagAdd callback functions to append/remove the values onto multiple inputs

**Comment by MaxITCorp** [comment]
Love this concept. However, I have a page that displays a series of images. User needs to be able to tag each image with one or more tags. Once all of the images are tagged, the user submits the form. How do I set up the HTML and Javascript to handle that? The tags would also need to be associated with the appropriate image being tagged.

**Comment by okcoker** [comment]
@MaxITCorp I'm still not sure what @barrychapman meant but for your scenario there are a fews ways I can think of.

- Once you construct the Taggle instance for each image, each instance can have a different input name using the `hiddenInputName` option upon construction.
- Upon constructing a Taggle instance, you can use `instance.setData({ imageId: 'image1' })` which you can then use `instance.getData()` later to know which image is associated with the tags, perhaps using something like `instance.getTags().values`
- Your container element that you use to construct the Taggle instance can have an attribute like `data-imageid="1"` on it which you can then retrieve later using `instance.getContainer().getAttribute('data-imageid')`

**Comment by KrisNick** [comment]
@okcoker brilliant! I can work with that. Thank you.

**Comment by okcoker** [comment]
@KrisNick cheers.

Not sure if that answers the original issue but let me know if not @barrychapman and we can reopen.
