### ISSUE TITLE
Vertical alignment of 'input focus' tag and previous tag text baseline

### ISSUE THREAD

**Issue by AaronNGray** [okcoker/taggle.js#110]
The vertical alignment of the text baseline of the 'input focus' tag and previously entered/existing tags is off !

I don't know if this is on purpose as its in all the examples but it does look wrong graphically.

**Comment by okcoker** [comment]
I don't see this as being an issue with the library itself since this is a matter of your own CSS. I'd glady accept any contributions to the minimal example here https://jsfiddle.net/okcoker/aqnspdtr/
