### ISSUE TITLE
Taggle input values

### ISSUE THREAD

**Issue by polrodoreda** [okcoker/taggle.js#112]
Trying to taggle input values on `<input id="labels" type="text" class="form-control" />` I obtain:

```js
taggle.js:325 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Taggle._setMeasurements (taggle.js:325)
    at new Taggle (taggle.js:316)
    at create:496
```

**Comment by okcoker** [comment]
I don't think you've configured things right. You should initiate Taggle on a div. See the docs [here](https://sean.is/poppin/tags/).
