### ISSUE TITLE
Support `Undo` operation

### ISSUE THREAD

**Issue by vikyd** [okcoker/taggle.js#113]
If I delete one tag, how can I undo the `delete` ?

Thx

**Comment by okcoker** [comment]
You would need to handle that in your application but the relevant hooks from the library that you can use are `onBeforeTagRemove(event, tag)`.

You could save the tag value before letting the remove happen. Then after the tag is removed re-add the saved tag.

Something like this https://jsfiddle.net/okcoker/t8yffak5/4/

**Comment by vikyd** [comment]
The example doesn't `undo` item in the original place

**Comment by okcoker** [comment]
I've added https://github.com/okcoker/taggle.js/issues/115 that would help with this.

If order matters for you, it just requires a little more code to readd the tags that were after the removed tag. Something like this https://jsfiddle.net/okcoker/t8yffak5/16/
