### ISSUE TITLE
Option for not auto trim space in start/end

### ISSUE THREAD

**Issue by vikyd** [okcoker/taggle.js#116]
Sometime I want to keep space as my value

**Comment by okcoker** [comment]
In what use case would anyone want to save an empty space into a tag?

**Comment by vikyd** [comment]
I use taggle.js as `Enum Input Box`, some user may input values like `abc  ` or `  abc`.

**Comment by okcoker** [comment]
Noticed this was only when typing tags in. Adding tags programatically (ie `instance.add('   tag')`) should already work.

I've added a `trimTags` option which defaults to true so in the next release you should be able to do `trimTags: false` for this use case

**Comment by vikyd** [comment]
@okcoker it works, but another problem: `Space can not be seen in created tags.`

**Comment by okcoker** [comment]
@vikyd can you use the `tagFormatter` option to replace the spaces with `&nbsp;`

it would probably look something like (untested):
```js
new Taggle({
    tagFormatter: function(li) {
        var textEl = li.querySelector('.taggle_text');
        textEl.innerHTML = textEl.textContent.replace(/\s+/g, '&nbsp;');
        return li;
    }
});
```
