### ISSUE TITLE
Grunt, RequireJS and minification issue

### ISSUE THREAD

**Issue by danielefenix** [okcoker/taggle.js#12]
I am working on a project based on RequireJS. I import taggle.js as dependence of one of my modules like this:

           define([ ...   'taggle'], function (... Taggle) { 

My RequireJS configuration has a shim configuration for taggle js
        
        "taggle" : {
            "deps": [ "jquery" ]
        }

I can correctly render the Taggle instance if the file is not minified

            this.taggle = new Taggle('.class', {
             ...
            }); 

I am currently experiencing some problem during the minification with Grunt of my project because it seems that Taggle is now undefined. I am using the requirejs plugin:

       requirejs: {
            compile: {
                options: {
                    baseUrl: "./lib",
                    paths: {
                        requireLib: "require"
                    },
                    mainConfigFile: "./main.js",
                    name: "../main",
                    out: "../dist/main.js",
                    removeCombined: true,
                    findNestedDependencies: true,
                    preserveLicenseComments: false,
                    include: 'requireLib'
                }
            }
        },

Do you have any clue about it?

**Comment by okcoker** [comment]
[This was just merged](https://github.com/okcoker/taggle.js/pull/25) so maybe try cloning the most recent and retrying with the UMD definition at the bottom?

Also the first argument to `new Taggle()` should be the DOM element or a string id of a DOM element

**Comment by spoonben** [comment]
@okcoker you might need to tag/release it for npm/bower

**Comment by okcoker** [comment]
@spoonben I know, I have a couple more things to do before I release this next version. I actually meant for @danielefenix to try cloning the most recent master branch and trying that :smile:

**Comment by spoonben** [comment]
@okcoker :smile: let me know what I can help with.
