### ISSUE TITLE
Better exception handler

### ISSUE THREAD

**Issue by sombek** [okcoker/taggle.js#121]
hello there I was using this library in my project 
And I did a small typo, and I tried to make better exception handling.
it is in `_createTag ` function. I did PR 

I think it needs the grunt thing or so

**Comment by okcoker** [comment]
How did you run into the issue here?

`_createTag` is an internal method and shouldn't be used by you.

**Comment by sombek** [comment]
Yes it’s an internal one.

‘’’new Taggle(“id”,{
tags: [a,b,c]
})’’’
When one of a,b, and c is not text it doesn’t stop, it goes and fire an error when making it to lowercase.
So I went there and added this throw thing

**Comment by okcoker** [comment]
Oh okay I see. Can you fix the code style so it passes the lint test. Also add a test for it. Otherwise I can add this in later.

**Comment by okcoker** [comment]
So I'm closing this because eventually i want to allow you to add objects in the tags array for purposes of #123
