### ISSUE TITLE
Taggle div loses label identifier

### ISSUE THREAD

**Issue by garethrees** [okcoker/taggle.js#125]
Here's our taggle-based form field:

![screen shot 2018-07-31 at 13 56 10](https://user-images.githubusercontent.com/282788/43460919-f8ec9ed8-94c9-11e8-94cd-2526609d82e3.png)

If I clicked on the "Keywords" label, I'd expect the form field to get focused, but it does not.

Here's the HTML that's generated:

```html
<div class="form-group">
  <label class="form-label" for="curated_link_keywords">Keywords<span class="form-hint">Type a comma, Return, or Enter to finish a keyword</span></label>
  <input class="form-control form-control-full-width js-keyword-picker" type="text" name="curated_link[keywords]" id="curated_link_keywords" style="display: none;">
  <div class="keyword-picker-fake-input form-control form-control-full-width">
    <ul class="taggle_list">
      <li><input type="text" class="taggle_input" tabindex="0" style="padding-left: 0px; padding-right: 0px;"></li>
    </ul>
    <div class="taggle_sizer" style="font-size: 19px;"></div>
  </div>
</div>
```

Taggle applies `display: none;` to our `curated_link_keywords` input and replaces it with its own, without the original `id="curated_link_keywords"` attribute.

Hope that makes sense?

**Comment by okcoker** [comment]
Since taggle uses it's own input, can you use something like:

```js
var input = instance.getInput();

input.id = 'curated_link_keywords';
```

**Comment by garethrees** [comment]
Thanks 🙇  , we'll try that out.

**Comment by okcoker** [comment]
@garethrees did that solve things for you?

**Comment by garethrees** [comment]
The project is in maintenance mode at the moment, so we haven't had chance to give this a try. We've linked to this issue upstream, so we'll get to it when we can and open a new issue if we can't get it fixed. Sorry for the super slow reply.
