### ISSUE TITLE
with jquery-ui autocomplete, autoFocus: true doesn't seem to work

### ISSUE THREAD

**Issue by davis** [okcoker/taggle.js#13]

**Comment by okcoker** [comment]
If you clone the repo and add `autoFocus: true` [here](https://github.com/okcoker/taggle.js/blob/232285e084e3caae5c6b663be46af88194eda7e4/assets/js/scripts.js#L26), it seems to work fine.

Only tested in OSX chrome

**Comment by davis** [comment]
ah, thanks for finally getting to this! :)
