### ISSUE TITLE
Doesn't  update bower (1.14.0 -> 1.14.1)

### ISSUE THREAD

**Issue by paul-4y** [okcoker/taggle.js#135]
Hello. Sorry, i'm little bit noobie:((

But may be you miss some step to update version? Mb in bower environment...

![1111](https://user-images.githubusercontent.com/31819072/49883012-7c31d900-fe3a-11e8-9072-124fc785f00d.jpg)

**Comment by okcoker** [comment]
Ahh sorry @paul-4y, I forgot to make the release on github!

I really should get this process automated... 😞 

Should be good to go now.
