### ISSUE TITLE
Possible forgot to make the release on github after build 1.14.1

### ISSUE THREAD

**Issue by paul-4y** [okcoker/taggle.js#137]
After install taggle.min.js looks like the same
bower cache was cleared

![image](https://user-images.githubusercontent.com/31819072/50007704-6d723000-ffba-11e8-92e4-ec70f2590acc.png)

**Comment by okcoker** [comment]
Good catch! I just updated that release to have the extra commit from the current master.

Can you try again and close if this fixes the issue?

**Comment by paul-4y** [comment]
Yes, now all right. Thanks:))
