### ISSUE TITLE
Feature Request: Total numbers of Tags

### ISSUE THREAD

**Issue by RajkiranShetty** [okcoker/taggle.js#142]
Option to add a limit to the tags. Currently, I am not able to set any limit to the tags.

**Comment by okcoker** [comment]
Hi @RajkiranShetty this already exists although the option is not on the docs for some reason. I'll add that, but the option key is `maxTags`. https://github.com/okcoker/taggle.js/blob/e3bb0ed27d019390c4d04caace3aa0e9f5397cb7/src/taggle.js#L138-L142

**Comment by RajkiranShetty** [comment]
Thank you
