### ISSUE TITLE
If saveOnBlur and maxTags are set the clearOnBlur does not work 

### ISSUE THREAD

**Issue by eppul** [okcoker/taggle.js#143]
Hi,

First of all, a great plugin that is easy to use.

I found a small bug,

I have options saveOnBlur set to true and maxTags set to 5.

When first 5 tags are set and user tries to set sixth tag the blurring does not clear the extra content.

Thank you
-Eppu

**Comment by okcoker** [comment]
What version are you on? You might be using an older version but this doesn't seem like an issue. Tested here: https://jsfiddle.net/zg7obs9n/

**Comment by eppul** [comment]
I mean the sixth should be removed when I click outside of the select to remove any confusion about what is searched.

**Comment by okcoker** [comment]
Hmmm in that case, maybe it'd be even better if you didn't even allow the user to be set up for failure. You can disable the input after the 5th tag is added, and re-enable the input if you decided to remove a tag like this: https://jsfiddle.net/1auzk8dm/

Another thought, you can also add your own blur event handler to the input after the `maxTag` limit is hit and remove it when a tag is removed. Example here: https://jsfiddle.net/9gpx6f0e/

**Comment by eppul** [comment]
Thank you.

I think I will implement the latter.
