### ISSUE TITLE
how to save input tags

### ISSUE THREAD

**Issue by KianSabzi** [okcoker/taggle.js#146]
is there any function or method for saving inserted tag by user that type them and show in <li> elements.?

**Comment by okcoker** [comment]
What do you mean "saving"? To a database or something?

**Comment by KianSabzi** [comment]
> What do you mean "saving"? To a database or something?

saving to the array and send to db. or something like this. for example send to function in back-end side.

**Comment by okcoker** [comment]
Taggle doesn't handle anything with databases. If you want to extract the filled in tags to send to your backend, you can do something like the following:

```js
var instance = new Taggle("test", {
    tags: ['These', 'are', 'prefilled', 'tags']
});

var values = instance.getTags().values;

// send array to your database via ajax or fetch or 
// whatever request library you're using

```
