### ISSUE TITLE
onBeforeTagAdd example?

### ISSUE THREAD

**Issue by BlkPingu** [okcoker/taggle.js#148]
Any way you could add an example to the docs on how to use `onBeforeTagAdd` to replace `duplicateTagClass` ?
It's just stated to be deprecated, but does not give any usage info here or anywhere else.
Currently having the issue that `onBeforeTagAdd` just adds a class to the tag that is the duplicate and the animation triggeres once, but the class is not temporary and stays there, thus even on trying to enter a duplicate twice for the same tag results in no feedback, which is was looking into solving with `onBeforeTagAdd`, but I'm lost as to how it's supposed to be used. 

Love your work btw

**Comment by okcoker** [comment]
Hi @BlkPingu you can do something like the following: https://jsfiddle.net/789nh4zw/1/

**Comment by BlkPingu** [comment]
10 / 10 thank you
