### ISSUE TITLE
Inbuilt handlers for input field focus/blur events

### ISSUE THREAD

**Issue by SujitSingh** [okcoker/taggle.js#149]
@okcoker this is a great plugin. Thank you for this.

Is there a way to use inbuilt focus/blur handlers added for the main input field?

I managed to do it by writing separate event handlers. Just wondering whether we have the option to use internal event listeners.

**Comment by okcoker** [comment]
@SujitSingh No there is no way. What reason would you have to do that?

**Comment by SujitSingh** [comment]
@okcoker I am intended to make tags editable(with remove icon) as soon as a user clicks on the input field and, non-editable as soon as the user clicks out of the input field.

**Non-editable -** 
![Non-editable](https://user-images.githubusercontent.com/26189654/75603231-8fd66780-5af2-11ea-9e97-92292917052b.png)

**Editable -** 
![Editable](https://user-images.githubusercontent.com/26189654/75603233-9533b200-5af2-11ea-8864-8ccd93a1565f.png)

Currently, I have added additional event listeners to achieve this behavior.

**Comment by okcoker** [comment]
Oh okay I would recommend adding a new event handler to the input as I think you have already. That way you're not messing with any internal functionality of the library itself.

This looks like a cool implementation btw!
