### ISSUE TITLE
configured submitKeys but seems doesn't work

### ISSUE THREAD

**Issue by CyborTronik** [okcoker/taggle.js#15]
I want to have tagging by default split by spaces also and have next configuration:
<code>
  new Taggle('tags', {submitKeys: [188, 9, 13, 32]});
</code>
but nothing changed.

**Comment by okcoker** [comment]
Are it's not something else interfering with your keys? I just did a fresh clone of the repo and used your key codes (Comma, Enter, Tab, Space) and it worked just fine.

**Comment by CyborTronik** [comment]
It works if you add space key direct into source code, but doesn't work during init as was described before

**Comment by Vizvamitra** [comment]
+1, `submitKeys: [9, 13]` but coma still adds a tag.
(I don't want to use 188 as a submit key because in my keyboard layout 188 key is a letter, not a coma)

**Comment by jimf** [comment]
Not sure if something was fixed/changed, but I just tested this (using the demo page) and it worked fine.

**Comment by okcoker** [comment]
@jimf I dont think I was ever able to reproduce. I'm going to go through all PRs and prune old issues pretty soon

**Comment by okcoker** [comment]
Pruning this since I was never able to reproduce. Feel free to post a jsfiddle with an example of this not working if this is still an issue
