### ISSUE TITLE
Cannot read property 'getBoundingClientRect' 

### ISSUE THREAD

**Issue by sshcli** [okcoker/taggle.js#157]
**Steps to reproduce the issue**
1. Go to the following demo page:
https://demo.simplejobscript.com/job/hybrid-mobile-developer-custom-apply-link-at-circles-remote/202
2. Open the console

**Expected behavior**
No error in console

**Actual result**
You will see this error:
```
taggle.js:298 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at Taggle._setMeasurements (taggle.js:298)
    at new Taggle (taggle.js:289)
    at 202:685
```

**System information (please complete the following information)**
taggle.js version: 1.15.0
PHP version: 7.4.14
Database version: MySQL 5.7.33

**Comment by okcoker** [comment]
This is not an issue with the library. This is an issue with the caller code:

<img width="588" alt="Screen Shot 2021-01-31 at 7 43 29 PM" src="https://user-images.githubusercontent.com/1030830/106403431-b84e9c00-63fc-11eb-9540-5222ca6b807d.png">


`$('.skillsTaggle.textarea')[0]` is undefined.

**Comment by sshcli** [comment]
Thanks!
