### ISSUE TITLE
Remove tag doesn't work

### ISSUE THREAD

**Issue by CyborTronik** [okcoker/taggle.js#16]
It would be nice to take care about best practices in designing components, I just found one potential issue with usage of getTagValues() it must not return original array but copy one.
Would be nice to have method 'removeAll' ass well.

**Comment by rictorres** [comment]
I agree with `removeAll()`. :+1: 
I already implemented it on my local and will go through the tests so I can make a PR today.

**Comment by okcoker** [comment]
Adding `removeAll` is fine but what is this ticket about?

**Comment by brettz9** [comment]
It sounds like @CyborTronik wishes for `getTagValues()` to return a clone of the `values` array--presumably so as to avoid modifications to those array contents to be reflected internally to Taggle.

**Comment by okcoker** [comment]
Ahhh thanks @brettz9. I understand now.
