### ISSUE TITLE
Input box does not get taller when there are enough tags to make it wrap to the second line

### ISSUE THREAD

**Issue by FoamyGuy** [okcoker/taggle.js#172]
When the user enters enough (or long enough) tags that the first row is fully occupied the tags automatically get wrapped to a second line. But the visual outline of the input box does not grow to accommodate, so the second line tags end up drawn on top of the bottom border of the input box, and 3rd or farther lines are below / outside of the input box.

![image](https://user-images.githubusercontent.com/2406189/163048919-27b946c3-8aa0-42e8-b0b8-9f27ccec463c.png)

To reproduce: On the test page https://sean.is/poppin/tags enter enough tags to cause it to wrap to the second line.

Is there a way to get the visual box that represents the input to grow when this wrapping occurs to match the amount of vertical space used?

**Comment by okcoker** [comment]
Thanks for reporting this. It should be fixed now. The fix was to add this rule to the css for the container element:

```css
.textarea.input:after {
    clear: both;
    content: '';
    display: block;
}

```

**Comment by FoamyGuy** [comment]
Thanks for your help, worked perfectly in my project. 

Also thanks for creating and maintaining this library, it's been a huge help for adding tagging utilities to a major project I work on. I poked around your Github profile and website and didn't find anything, but wanted to ask if you have any way set up for folks to send you financial support? If you do have something set up I'd be happy to throw some bucks your way to buy some orange juices (or whatever else you want).

Thanks again.

**Comment by okcoker** [comment]
>  I poked around your Github profile and website and didn't find anything, but wanted to ask if you have any way set up for folks to send you financial support?

Hey @FoamyGuy that would be awesome and very kind of you. I never really thought about it until you mentioned it so I just set up Github Sponsors [on my account](https://github.com/sponsors/okcoker). Admittedly it's not very sexy compared to some other accounts I've seen but I can work on that in the near future.
