### ISSUE TITLE
Provide a minimal CSS that make it look good

### ISSUE THREAD

**Issue by yohcop** [okcoker/taggle.js#24]
There is no css in dist, and the css in assets (taggle.css) does a bit too much (such as setting a background picture, styling h1,h2, pre, p, etc)

It would be extremely useful to have a basic CSS file that one can drop in their project without having to do too much customization (i.e. reasonable defaults)

Thanks!

**Comment by omichelsen** [comment]
:+1:

**Comment by aviemet** [comment]
I second this, except that I would want some basic and very extensible Sass definitions.

**Comment by okcoker** [comment]
You can use [this section](https://github.com/okcoker/taggle.js/blob/026a2f96158acac12813c53bec8672d4556f2f37/assets/scss/taggle.scss#L148-L311) of the scss file. I'm also open to having different examples if you want to design some yourself, similar to the stackoverflow and delicious styles at the bottom of that file.
