### ISSUE TITLE
Failing recognition of last list item

### ISSUE THREAD

**Issue by straight-shoota** [okcoker/taggle.js#34]
I'm using taggle together with [type-ahead](https://github.com/marcojetson/type-ahead.js) for autocompletion.

Type-ahead inserts a list of suggestions right after the `.taggle_input` element, wrapped in ul and li elements. When a suggestion gets selected and the tag is to be added, the `Taggle.add` function breaks because `self.list.querySelectorAll('li')` doest not target only the direct descendants of `.taggle_list`. Therefore insertBefore throws an exception because the selected lastLi is not a child of the taggle list but rather an item in the suggestion list.

This is quite easy to fix, but there are different possibilities and I'm not sure which one is the best.
I just expanded the selector to `self.list.querySelectorAll('li.taggle')` and used `lastLi.nextSibling` to get the right target for insertBefore. It would also be able to set a specific class on the last li which holds the input. Or maybe just use `self.list.children`? The li containing the input should always be the last item...

Having this fixed, the integration with type-ahead works pretty well.

**Comment by okcoker** [comment]
Ah I see the problem. I'm thinking `.children` should be fine. Does that work for you?

Not sure about `type-ahead`'s other options or how you're using taggle to work with it but it _kinda_ works here http://jsfiddle.net/m6n0z8ww/

**Comment by straight-shoota** [comment]
My solution with `querySelectorAll('li.taggle')` won't work when there are no tags since this function would return an empty array. I didn't recognize this before because I always had some tags prefilled.
`.children` works for me and I can't think of any reason why it shouldn't. Since the input is always spans the remaining space, there cannot really be anything else behind it.

Unfortunately I encountered some trouble with key events. When selecting an item from the autocomplete list and hitting enter or tab, the key event on the input attached by taggle fires first and adds the current partially typed key word as tag. Only after that, type-ahead adds the suggested tag. Only using the mouse to select a suggestion works fine.
So I guess I'll either have to fiddle with the event handlers or look for a different solution... But I'd like not to use any heavy frameworks.

**Comment by okcoker** [comment]
That makes sense. Let me mess around with type-ahead and ill figure out a solution.

**Comment by okcoker** [comment]
So @straight-shoota basically, it looks like you want to ignore Taggle's events and only add tags based on typeahead stuff. With the soon-to-be-added change of `.children` you should be able to do this:

(The more important stuff is at the bottom of the JS pane)
http://jsfiddle.net/m6n0z8ww/2/
