### ISSUE TITLE
Possible to bind tag creation to spacebar?

### ISSUE THREAD

**Issue by bradfrost** [okcoker/taggle.js#37]
Hi there, 
I'm wondering if it's possible to create a tag when the `spacebar` is pressed rather than the `enter` key. Does this option exist, or would it need to be a modification? Thanks!

**Comment by jimf** [comment]
Hi Brad. Taggle splits on comma, tab, and enter by default, and this behavior can be overridden with the `submitKeys` option:

```js
var taggle = new Taggle('tags', {
    submitKeys: [
        188, // comma
        9,   // tab
        13,  // enter
        32   // space
    ]
});
```

**Comment by bradfrost** [comment]
Hey @jimf, thanks so much for the quick response! This works perfectly, thanks!

**Comment by okcoker** [comment]
@jimf :+1:
