### ISSUE TITLE
Hashtag support

### ISSUE THREAD

**Issue by bradfrost** [okcoker/taggle.js#38]
Hi there,
I'm wondering if the script supports handling hashtags (#) when creating tags. Here's what I'm trying to accomplish:

A user can create a tag with a hashtag by simply typing "#hashtag", and the pound sign would be baked into the string of the tag. 

However, if the user omits the pound sign when creating a tag (e.g. "hashtag"), the script would add the pound sign to the string when the tag is created. This behavior is similar to how Tumblr operates:

![hashtag](https://cloud.githubusercontent.com/assets/383701/11548073/d05bd354-9926-11e5-80cd-ecfe979441ec.gif)

Is this possible with this library? Thanks!

**Comment by jimf** [comment]
I don't believe there's currently a great way to format the tags. However, you *can* do something like the following:

```js
var taggle = new Taggle('tags', {
    onTagAdd: function(event, tag) {
        if (tag[0] !== '#') {
            taggle.remove(tag);
            taggle.add('#' + tag);
        }
    }
});
```

If you're doing anything with the add event already, you'll just need to be mindful that you'll sort of get 2 events in the cases that # is omitted.

**Comment by okcoker** [comment]
Thanks @jimf for the reply.

Jim's solution looks like it could work. You can also use the `tagFormatter` option and do something similar without adding or removing if you'd prefer:

```js
var taggle = new Taggle('tags', {
    // Formats the `li` to be appended to the list of tags
    tagFormatter: function(li) {
        // Grabs the span with the text inside
        var node = li.querySelector('.taggle_text');
        var text = node.textContent;
        if (text.indexOf('#') !== 0) {
            node.textContent = '#' + text;
        }
        return li;
    }
});
```

**Comment by bradfrost** [comment]
@okcoker this solution works perfectly for me. Thanks for your help, guys!
