### ISSUE TITLE
Add option to limit number of tags

### ISSUE THREAD

**Issue by kazzkiq** [okcoker/taggle.js#39]
It would be interesting to add an option to block tags when the number hit a mark.

Example:
```js
let taggle = new Taggle('my-element', { maxTags: 5 }) // don't add more tags after 5 items
```

Right now I think the only way to achieve this is to use `.onBeforeTagAdd()` to check number of tags and block the new addition.

Badass plugin btw.

**Comment by okcoker** [comment]
Thanks!

I think this could be a useful option. I will consider adding it within the next release since it's still possible to achieve this functionality using the suggestion you already mentioned.

**Comment by okcoker** [comment]
@kazzkiq this is in the newest release

**Comment by kazzkiq** [comment]
Nice!
