### ISSUE TITLE
Taggle example with minimal styles needed

### ISSUE THREAD

**Issue by ruffin--** [okcoker/taggle.js#40]
I'm trying to install Taggle without any build overhead. Getting it up and running minimally isn't that difficult -- just include taggle.js and taggle.css. 

taggle.css is a little overfilled, however, changing styling for some top-level elements, like `h1`, `pre`, `p`, etc, which are things I'd rather not have taggle mess with. Taking out everything that doesn't start with `.taggle_` actually works fairly well, but it doesn't look great:

* The *Enter tags...* message floats above where the "real" taggle editor is.
* There's no visual cue for where the tags should go.
* The "close tag" *X*s are not centered, etc

Taggle obviously expects some sort of UI framing that isn't mentioned in the "Creating a basic taggle" instructions (and that I assume npm and Bower provide somehow ??).

I'd really like to get this into a text input sized display... How tough would it be to add a tutorial for quickly skinning without npm/Bower/any overhead?

Just fwiw, here's the very simple page I'm using to test:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html>
        <head>
            <title>jqGrid Testing</title>

            <script type="text/javascript" src="./taggle.js"></script>
            <link rel="stylesheet" type="text/css" href="./taggle.css" />
         </head>

        <body>
            <div id="example1"></div>
            <script>new Taggle('example1');</script>
        </body>
    </html>

... and I've got taggle.css pared down to this...

    .taggle_list {
      float: left;
      width: 100%;
    }

    .taggle_input {
      border: none;
      outline: none;
      font-size: 16px;
      font-weight: 300;
    }

    .taggle_list li {
      float: left;
      display: inline-block;
      white-space: nowrap;
      font-weight: 500;
      margin-bottom: 5px;
    }

    .taggle_list .taggle {
      margin-right: 8px;
      background: #E2E1DF;
      padding: 5px 10px;
      border-radius: 3px;
      position: relative;
      cursor: pointer;
      transition: all .3s;
      -webkit-animation-duration: 1s;
              animation-duration: 1s;
      -webkit-animation-fill-mode: both;
              animation-fill-mode: both;
    }

    .taggle_list .taggle_hot {
      background: #cac8c4;
    }

    .taggle_list .taggle .close {
      font-size: 1.1rem;
      position: absolute;
      top: 5px;
      right: 3px;
      text-decoration: none;
      padding-left: 2px;
      padding-top: 3px;
      line-height: 0.5;
      color: #ccc;
      color: rgba(0, 0, 0, 0.2);
      padding-bottom: 4px;
      display: none;
      border: 0;
      background: none;
      cursor: pointer;
    }

    .taggle_list .taggle:hover {
      padding: 5px;
      padding-right: 15px;
      background: #ccc;
      transition: all .3s;
    }

    .taggle_list .taggle:hover > .close {
      display: block;
    }

    .taggle_list .taggle .close:hover {
      color: #990033;
    }

    .taggle_placeholder {
      position: absolute;
      color: #CCC;
      top: 12px;
      left: 8px;
      transition: opacity, .25s;
      -webkit-user-select: none;
         -moz-user-select: none;
          -ms-user-select: none;
              user-select: none;
    }

    .taggle_input {
      padding: 8px;
      padding-left: 0;
      float: left;
      margin-top: -5px;
      background: none;
      width: 100%;
      max-width: 100%;
    }

    .taggle_sizer {
      padding: 0;
      margin: 0;
      position: absolute;
      top: -500px;
      z-index: -1;
      visibility: hidden;
    }

Thanks!

**Comment by okcoker** [comment]
> however, changing styling for some top-level elements, like h1, pre, p, etc, which are things I'd rather not have taggle mess with. Taking out everything that doesn't start with .taggle_ actually works fairly well, but it doesn't look great:


Taggle was made so that the consumer has full control over how they want to style things. I'd imagine since you dont (and probably nobody else for that matter) want any of the base element styling, you'll have to add some of those rules to the `.taggle_` prefixed classes. Things like `<ul>` elements for example, have a default margin/padding in most browsers by default, so `.taggle_list` may have to have some of those normalizing style rules added in order to accomplish what you're trying to do.

That being said, I do think it could be worth it to create a jsfiddle of some sort where it only uses `.taggle_` prefixed classes. As a quick example I'm able to reproduce (what you're probably seeing) [here](http://jsfiddle.net/m6n0z8ww/3/). I can look into making that example a little better so that it doesn't add unnecessary styling to base elements.

And as always, feel free to update it yourself if you'd like, as I'm sure it would be helpful to others in the future.

**Comment by okcoker** [comment]
These are pretty minimal http://jsfiddle.net/okcoker/m6n0z8ww/6/
