### ISSUE TITLE
Possibly add an inputClass: [String='' "]  for the .taggle_input.

### ISSUE THREAD

**Issue by RFzees** [okcoker/taggle.js#41]
Hi, and thank you for this awesome contribution to the web, I personally love Taggle and how easy it is to use. 

I have been trying to style multiple **taggle_input(s)** with different styles on the same page.
It would be great if you could add an **inputClass: [String='' "]**  for the **.taggle_input** to make it easier to style multiple taggle inputs on same page.

**Comment by okcoker** [comment]
Hey @RFzees glad you find it useful! 

You should be able to do this no problem already as seen on the "[Misc - Tags around the web](https://sean.is/poppin/tags)" section.

All you need to do is add a separate class on each taggle container and you should be able to do something like:

```css
.container1 .taggle_input { // styles }

.container2 .taggle_input { // different styles }
```

**Comment by RFzees** [comment]
Right, lol. Thank you :)
