### ISSUE TITLE
unexpected tag creation on «comma» keypress in different layout

### ISSUE THREAD

**Issue by 2korzhik** [okcoker/taggle.js#43]
In russian keyboard layout comma key reside «б» char so pressing it while typing word containing «б» char fires tag creation which makes imposible to create tags containg «б» char.

**Comment by okcoker** [comment]
You can use the [`submitKeys`](https://github.com/okcoker/taggle.js/blob/91b21a2f1ff36a8754cf4d54afaeb42422e7228b/src/taggle.js#L99) option to set whatever keys you want to be the trigger for tag creation. It just defaults to comma, tab, and enter.
