### ISSUE TITLE
saveOnBlur option prevents placeholder from re-appearing when no tags present

### ISSUE THREAD

**Issue by solomonhawk** [okcoker/taggle.js#45]
I'm actually not sure if this is a bug - what's the intended interaction between `options.saveOnBlur` and the showing and hiding of the placeholder element?

[These 3 lines](https://github.com/okcoker/taggle.js/blob/master/src/taggle.js#L560-L562) will never get executed if `options.saveOnBlur` is true.

Moving them after the `if/else` block is a simple fix and allows the placeholder to be visible again when blurring the field with no tags in it.

**Comment by okcoker** [comment]
Hmm I think you are right! Will try to get a fix in with some tests later tonight.
