### ISSUE TITLE
Will the example file be updated every release?

### ISSUE THREAD

**Issue by kennynaoh** [okcoker/taggle.js#53]
Because the example is not a distributed purpose directory.
And the minified file is in that directory.
So I want to ask will the example file be updated every release?
Thanks!

https://github.com/cdnjs/cdnjs/issues/7925
https://github.com/cdnjs/cdnjs/pull/7954

**Comment by okcoker** [comment]
[Yup!](https://github.com/okcoker/taggle.js/blob/master/Gruntfile.js#L62)

**Comment by kennynaoh** [comment]
Thanks for your help!
