### ISSUE TITLE
Difficult (impossible?) to get working with normalized databases

### ISSUE THREAD

**Issue by bfischer1121** [okcoker/taggle.js#57]
I guess this library works well for a denormalized table where the tags are part of a string column. It doesn't work well for web apps that run on primary/foreign keys that aren't shown to the user, because what's passed in the events, etc. is almost always some (possibly) non-unique display text shown to the user. The merging of the 2 concepts (display text and id) just makes it very difficult to use.

**Comment by okcoker** [comment]
Not sure what you mean. Do you mean each tag should have an internal ID as well as the tag text for each of the events?

**Comment by bfischer1121** [comment]
Yes, I need a way to set ids and retrieve them within the events and api. I don't know how people are maintaining data integrity otherwise. For instance, I'm creating a messaging app where you type a person's name, tap on the autocomplete item, and it adds it as an entry. Since this only supports the display text I would need to depend on a person's name to be the relation. When they submit the form I have no way to reliably match that name to an id. 2 "Muhammad"'s and kaboom!

**Comment by okcoker** [comment]
I will make this the default in 2.0 👍

**Comment by bfischer1121** [comment]
Nice work!
