### ISSUE TITLE
onBeforeTagRemove async

### ISSUE THREAD

**Issue by webchaz** [okcoker/taggle.js#59]
Using `confirm` works with this method to return true or false because it's synchronous.  However, trying to return true or false asynchronously doesn't work.

For example:

```
onBeforeTagRemove: function(event, tag) {
   customAsyncAlertMethod(function(response) {
       if (response) return true;
       return false;
    });
});
```

This won't work.  Is there another way to get around this?  Thank you

**Comment by okcoker** [comment]
Hmm... currently no but that would definitely be useful. I could see the implementation working something like the below maybe:

```js
onBeforeTagRemove: function(event, tag, callback) {
   customAsyncAlertMethod(function(response) {
       if (response) callback(true);
       callback(false);
    });
});
```

Thoughts?

**Comment by webchaz** [comment]
Definitely, that would be perfect.

**Comment by webchaz** [comment]
@okcoker Do you think this is something you'd be able to implement? So far, taggle's been great by the way!

**Comment by okcoker** [comment]
Yea, sorry just have been really busy. Will get on this ASAP. I do agree its an important feature.

**Comment by webchaz** [comment]
No problem! Figured I'd just check in to see if you think you'll have time to add this.

**Comment by okcoker** [comment]
Hey @webchaz made the callback more node style so you just call the callback with no arguments to pass, or with any truthy value if there was an error. 

Updated the example above for how this would work

**Comment by webchaz** [comment]
This is great! Would you be able to add the same to the `onBeforeTagAdd` event also?

**Comment by okcoker** [comment]
That's partly why this took a while. I'd like the API to be consistent in that way but adding to `onBeforeTagAdd` would require a bit more reworking.

**Comment by webchaz** [comment]
Ah ok, maybe I can take a look and see if I can put in an update for it - This is the last piece of the puzzle :).  Looks like the new changes aren't in npm though?

**Comment by okcoker** [comment]
Wanted to wait for the remaining issues, but if you wanna look into implementing `onBeforeTagAdd` feel free :)
