### ISSUE TITLE
Provide autocomplete array with labels and values - Bug!

### ISSUE THREAD

**Issue by Twisterking** [okcoker/taggle.js#63]
So when I use an array of objects with `label` and `value` for my autocomplete, the value is used to the text of my taggle tag and not the label.
So let's say:
```
        var jobfields = new Taggle('jobfields');
        var container = jobfields.getContainer();
        var input = jobfields.getInput();

        var alljobfields = [{ label: 'javascript', value: 'abc123'}, { label: 'node', value: 'xyz789'}];

        $(input).autocomplete({
            source: alljobfields,
            appendTo: container,
            position: { at: "left bottom", of: container },
            select: function(event, data) {
                event.preventDefault();
                if (event.which === 1) {                    
                    jobfields._add(data.item.label);
                }
            }
        });
```

If I type "javas" the autocomplete suggest "javascript". onenter the text "javascript" should be used for the tag, but "abc123" is used instead! Please fix this! Only having simple text based tags is not enough for me.

**Comment by okcoker** [comment]
Ok well this is not a bug with Taggle. This is how [jQuery's autocomplete works](http://api.jqueryui.com/autocomplete/#option-source). If you're providing an array of objects, the plugin will fill the input with the value of `value`. If your data structure needs to be an object, just rename `value` to some other key. `data.item` will contain whatever you put in the object. 

Demo below:

http://jsfiddle.net/okcoker/j5yeon1x/
