### ISSUE TITLE
Readme only!

### ISSUE THREAD

**Issue by rrmdp** [okcoker/taggle.js#64]
Hi there, thanks for this nice script. It would be nice to have a readme only option... so when 'true' just show tags and don't let user to edit,add,remove them.

**Comment by okcoker** [comment]
What did you have in mind for preventing editing/adding? Just not append the remove button to the list items? Would adding the [`readonly` or `disabled`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) attribute to the input not suffice for your use case?

**Comment by rrmdp** [comment]
Probably the 'disabled' attribute it is enough however I'd preffer to don't even render de input filed. Also I'd set the the tags as <a> for redirecting (to the url that shows all the items with the selected tag).
Thanks

**Comment by okcoker** [comment]
Hmm your use case seems pretty specific. I'd rather not add extra options if you can accomplish this with the available methods, especially since 2.0 will deprecate certain options for the same reason.

You could use `taggle.getTags().elements` to do whatever you'd like with the tags and you can use `taggle.getInput()` and remove the input if you'd rather it not be there.

**Comment by okcoker** [comment]
I think what you're looking to do is just display a list of tags which wouldn't require this library at all. You can use this library to gather the tags, maybe save them to a DB, and then display them as list items. You can also, of course, take the suggestion mentioned above.

**Comment by rrmdp** [comment]
It's very common in tagging to allow or not users to add/delete tags, in my case I only allow if a user is registered within the platform therefore an option for readme only so on 'true' the script wont render the input, placeholder, etc would make things much easier, any way I've already sorted it out. Thanks and hope you add the option :)

**Comment by okcoker** [comment]
Can you send a PR so we can see what this might look like as an implementation? Or maybe edit this fiddle [here](https://jsfiddle.net/okcoker/s5yx2yc1/) and show me what it'd look like?

**Comment by rrmdp** [comment]
I didn't change snything in your script, I've used the 'tagFormater'. No very happy about it as there is not point to render the input, close button and then remove() .
