### ISSUE TITLE
Sizing issues when using taggle in ng-dialog/angular

### ISSUE THREAD

**Issue by robotron2084** [okcoker/taggle.js#69]
When attempting to add tags to a Taggle input in a dialog, Taggle does not correctly measure the width at startup. This causes the input field to be 10px wide. This could be because items are currently animating or displaying and have an invalid width and the fallback value is 10px.

Steps to reproduce:
 * Create a website with Angular and ng-dialog.
 * Dynamically create a Taggle object within a modal using Angular (you'll need to wait a frame for Angular to attach the element to the dom, then you can create a taggle a la new Taggle()).
 * Open the modal and observe that the Taggle field displays.
 * Click within the field and start typing.
 * Observe that the type displays in a 10px wide div.

There are probably other various steps to repro that do not involve ng-dialog and angular, but this is my current setup.

Expected Results:
Even in animated modals Taggle should display input fields correctly.

Potential Fix:
I have been able to fix the issue by calling this._getMeasurements at the beginning of _fixInputWidth(). This does seem to work as expected and I don't think this is too much of a performance concern.

**Comment by okcoker** [comment]
That doesn't seem like a bad solution. 

So I've ran into problems with things like this before relating to modals or elements within other elements that are resizing, therefore the inner element size calculations get thrown off. What if there were a `resize` listener added that called `_getMeasurements()`? Would that also fix your issue? The less we can thrash the DOM with calculated styles the better. I also fully realize if a resize handler doesn't work, your suggestion would be fine as far as performance goes.

**Comment by robotron2084** [comment]
I am not much of a web developer, so I'm unsure how the resize logic would be better/worse. :)
It does seem more logical since we would want to remeasure when we resize.

**Comment by okcoker** [comment]
Do you think you could provide a simple JSFiddle of what you're experiencing? I'm not the most familiar with angular.

**Comment by robotron2084** [comment]
I shall try to use JSFiddle to de-angularify the problem and get you a better repro. Will repost when I get to it.

**Comment by robotron2084** [comment]
https://jsfiddle.net/uxtuo9p6/1/

Ok, there it is. This is quite analogous to the problem I'm having. The animation is required to break Taggle.

PS: First time making something in JSFiddle and using JQuery UI, hope I did it right!

**Comment by robotron2084** [comment]
Great! Thanks, man.
