### ISSUE TITLE
No css?

### ISSUE THREAD

**Issue by jakobrosenberg** [okcoker/taggle.js#7]
I can't seem to find the css files for your project. All I can find are the compiled css files for the entire example page.

**Comment by rikukissa** [comment]
It would probably be a good idea to ship a CSS file containing only the css needed for the tag-input component itself. Majority of people (including myself) doesn't want to include the html, .btn etc style definitions to their projects.

**Comment by davis** [comment]
+1 -- especially because a lot of these styles have !important on them :(

**Comment by okcoker** [comment]
The `!important` styles are specific to my site at the moment or overriding jQuery's autocomplete. They aren't in any way specific to Taggle. Feel free to just delete what you don't need.

**Comment by nparziale** [comment]
+1 couldn't make it work but it looks great on your demo.

**Comment by CanRau** [comment]
Think too a default style would be a nice starting point. Just noticed that * box-sizing:border-box; makes the input appear below the tag list.. for me after 2 tags the input jumps down content-box on taggle_list fixed this for me
