### ISSUE TITLE
Firefox: input width

### ISSUE THREAD

**Issue by jonatanklosko** [okcoker/taggle.js#71]
Hi, look at [this fiddle](https://jsfiddle.net/285htso6/) in Firefox (47.0 here). You should see that the input has constant `10px` width. I investigated it and found out that [these lines](https://github.com/okcoker/taggle.js/blob/master/src/taggle.js#L279-L280) are the reason. They lead to setting some variables to NaN and at the end the `_setInputWidth` function sets the input to `10px`. After logging to console I realised that both `style['border-left']` and `style.borderLeft` (same for right) are empty strings even if the border is set to something reasonable, on the other hand `style.borderLeftWidth` contains the appropriate number of pixels. The weirdest is that the demo page works even in Firefox, I cannot figure out why.
Changing these lines to the following fixes it for me:
```javascript
var lborder = parseInt(style['border-left'] || style.borderLeft || style.borderLeftWidth, 10);
var rborder = parseInt(style['border-right'] || style.borderRight || style.borderRightWidth, 10);
```

**Comment by okcoker** [comment]
Ah yes, the border part is kinda new but I think it should always be `style['border-left-width'] || style.borderLeftWidth` as the border style is not important. Do you wanna send a PR?

**Comment by jonatanklosko** [comment]
Sure =)
