### ISSUE TITLE
Include defauld css in the package

### ISSUE THREAD

**Issue by jonatanklosko** [okcoker/taggle.js#72]
The style from the demo page is pretty sweet but using it is kinda troublesome because the css from example contains not-related things like buttons headers and the whole page. It would be cool to separate just the taggle specific css and include it in the package =)

**Comment by okcoker** [comment]
Yea #40 kinda touched on this. Here is a very basic style'd example with minimal css https://jsfiddle.net/okcoker/s5yx2yc1/
