### ISSUE TITLE
[feature request] add disable() method

### ISSUE THREAD

**Issue by molayli** [okcoker/taggle.js#74]

**Comment by okcoker** [comment]
Disable for the input? You should be able to do

```js
taggle.getInput().setAttribute('disabled', '')
```

**Comment by molayli** [comment]
No I mean the entire tags container , but this solution is good enough , I'll add a transparent layer to block the tag removal option

**Comment by okcoker** [comment]
That works.

You can also use css to disable any removal clicks with

```css
.container {
    pointer-events: none;
}
```

**Comment by molayli** [comment]
Thanks for the quick reply and for this awesome plugin.
