### ISSUE TITLE
tagFormatter() not called on add

### ISSUE THREAD

**Issue by highvoltag3** [okcoker/taggle.js#79]
The `tagFormatter` works fine when the `tags:` option gets read on toggle instantiation, but it does not get called when new tags are added.

**Comment by okcoker** [comment]
How are you adding new tags?

if you're calling `add()` that should internally call `_add` which calls `_createTag` which calls `tagFormatter`

**Comment by highvoltag3** [comment]
I'm using `add()` and it's not calling tagFormatter :(

**Comment by okcoker** [comment]
seems to be working fine here: https://jsfiddle.net/okcoker/s5yx2yc1/2/

**Comment by highvoltag3** [comment]
Yeap, traced it back to an error on the code I wrote to format the tag.

Thanks!
