### ISSUE TITLE
Adding data to each tag

### ISSUE THREAD

**Issue by gr33k1718** [okcoker/taggle.js#81]
Hello there,

I have a need to add html data attributes to each tag. I have been trying to come up with a way to do this for a number of hours now and cannot seem to crack it.

I see no way this can easily be done and in a future release i would ask if you add this ability.

Many thanks

**Comment by gr33k1718** [comment]
Ok just discovered tagFormatter, no need to reply. Oversight from me

**Comment by okcoker** [comment]
No worries!
