### ISSUE TITLE
Detect when the plugin is fully loaded

### ISSUE THREAD

**Issue by DaPo** [okcoker/taggle.js#82]
Hello there,

First of all, very nice plugin. I enjoy a lot working with it. Great job and thank you!

I have a question for you: is there any way to detect when the plugin is loaded? Like having something like this:
```JavaScript
var taggle = new Taggle('list-tags', {
            callback: function() {
              console.log("Fully loaded!");
            }
});
```

Thank you!

**Comment by okcoker** [comment]
Hey @DaPo what do you mean "fully loaded"? Since the instantiation is synchronous, couldn't you just do:

```js
var taggle = new Taggle('list-tags');
console.log("Fully loaded!");
```
