### ISSUE TITLE
TagFormatter custom tag 

### ISSUE THREAD

**Issue by turkle12** [okcoker/taggle.js#87]
Hi I'm trying to return a custom tag using TagFormatter. I'd like to return the below but I'm unsure how to do so. Any pointers if it's possible would be much appreciated. Thanks! 

```
<li>
   <a href='' class="searchTag searchTag-isActive">             
     <div class="searchTag-term">
       <span class="searchTag-term-doctype">Doc type:</span>
       <span class="searchTag-term-name">Study</span>
     </div>
     <span class="searchTag-delete">
       <img src="assets/img/icons/close.svg" alt="">
      </span>    
    </a> 
 </li>

```
<img width="173" alt="screen shot 2017-01-23 at 20 20 24" src="https://cloud.githubusercontent.com/assets/1423478/22221103/6a3105f0-e1a9-11e6-8807-adbfc4ed22a3.png">

**Comment by okcoker** [comment]
The `tagFormatter` option is really for minor changes. The close button that is inside the li already has the event listener to remove the tag so you'll have to style it based on the class names provided to you. As of right now it needs to be a direct child of the `li` element.

You should easily add "Doc type:" though. Assuming "Study" is the tag name entered in the input you can probably do something like [this](https://jsfiddle.net/okcoker/aqnspdtr/4/).

The styling of the tag is completely up to you but it is definitely possible to achieve that.

**Comment by turkle12** [comment]
Thanks for the help! 

I ended up using ES6 template literals and styling the elements with classes: 

```
li.innerHTML = '
<a href='' class="searchTag searchTag-isActive">             
     <div class="searchTag-term">
       <span class="searchTag-term-doctype">Doc type:</span>
       <span class="searchTag-term-name">Study</span>
     </div>
     <span class="searchTag-delete">
       <img src="assets/img/icons/close.svg" alt="">
      </span>    
    </a> '
```

**Comment by okcoker** [comment]
So the only problem with that is that you wont be able to remove the tag since you're erasing the close button that has the event handler attached. You'll have to do some more DOM manipulation

**Comment by turkle12** [comment]
Sorry, the above was a cut & paste job. Here's what I actually put and it's working. I kept the close button like you said. 

```
var tagText = li.querySelector('.taggle_text');
var text = tagText.textContent;
var closeButton = li.querySelector('.close');

closeButton.classList.add('searchTag-delete');
li.classList.add('tag');
tagText.innerHTML = `<a href='' class="searchTag searchTag-isActive">             
        <div class="searchTag-term"> 
             <span class="searchTag-term-name">${text}</span>
          </div>
          </a>`
closeButton.innerHTML = '<img src="assets/img/icons/close-icon.svg" alt="">';
return li;
