### ISSUE TITLE
"Enter tags..." doesn't come back after removeAll()

### ISSUE THREAD

**Issue by arlorose** [okcoker/taggle.js#88]
Hi,

I have an app where I can click on an existing item that has tags, and they populate. But when I create a new item, I clear out all the values from the entry fields... part of that is calling removeAll() on my taggle instance... and while all the tags go away, the placeholder "Enter tags..." doesn't appear. If I click into it and back out it shows up.

Ever seen this before? Am I clearing out the tags incorrectly?

**Comment by okcoker** [comment]
Interesting. This is a bug. In the meantime, here's a solution until that gets fixed:

https://jsfiddle.net/okcoker/eb3o47b3/8/

Just focus & blur the input programatically.

**Comment by okcoker** [comment]
Released! https://www.npmjs.com/package/taggle

**Comment by arlorose** [comment]
Thank you!
