### ISSUE TITLE
New Settings

### ISSUE THREAD

**Issue by rabobadilla** [okcoker/taggle.js#89]
Excellent work 👍 , but i think that are necessary 3 new ssettings in var DEFAULTS 

 minimumTagLength,
 maximumTagLength,
 regularExpression 

I modified the js, cause these settings are imperative for me. :)

Finally my instantiation of a Tag is:

var local = new Taggle($('.local.textarea')[0], {
    duplicateTagClass: 'bounce',
    placeholder: 'Ingrese una etiqueta',
    maxTags: 2,
    minimumTagLength: 3,
    maximumTagLength: 20,
    regularExpression: '^[a-zA-Z0-9 á é í ó ú Á É Í Ó Ú ñ Ñ]*$'
});

**Comment by okcoker** [comment]
You can currently achieve this functionality using `onBeforeTagAdd`? Just run your checks in that callback function and return false if they don't pass.

**Comment by rabobadilla** [comment]
Ok, thx
