### ISSUE TITLE
[Options] Typo in the "delimiter" option name

### ISSUE THREAD

**Issue by eledhwen** [okcoker/taggle.js#91]
Hi there,

So uh, that's no big deal but I've just stupidly spent a wee bit too much time trying to figure out why the "delimiter" option didn't work, only to notice that there was in fact a typo and Taggle expected it to be written "delimeter" (that's also reflected in the documentation, so I guess it works as advertised).

Maybe it could be a good thing to support "delimiter", and maybe preserve BC for some time by re-routing "delimeter" options to "delimiter".

**Comment by eledhwen** [comment]
Also, some mechanism to catch undefined options could help in those situations :-)

**Comment by okcoker** [comment]
Oh wow. 👍
