### ISSUE TITLE
How to using getValue method?

### ISSUE THREAD

**Issue by celalnuriakgun** [okcoker/taggle.js#95]

**Comment by okcoker** [comment]
Whats the problem here?

**Comment by celalnuriakgun** [comment]
I know a bit of JavaScript. Do you have a video for us? For now the problem is: Where will I print when I retrieve the tags from the database? I'm from Turkey, I know little English.

**Comment by celalnuriakgun** [comment]
I guess i found how i can do it, thanks for this work. :)

**Comment by okcoker** [comment]
No problem!
