### ISSUE TITLE
getContainer() — Uncaught TypeError: Illegal invocation problem

### ISSUE THREAD

**Issue by celalnuriakgun** [okcoker/taggle.js#96]
When I'm using getContainer(), get error Uncaught TypeError: Illegal invocation problem in my console. What can I do? 

My code:
var taggle = new Taggle('example1', {
   placeholder: 'Favori etiketlerim: (bkz: sokak hayvanları, göktaşı)',
   allowDuplicates: true,
   disallowedTags: ['apple']
   });
$('#submit').click(function(){
   var tit = $('#title').val();
   var cat = $('#cat').val();
   var testt = taggle.getContainer();
   console.log(testt);
   $.ajax({
      method: "POST",
      url: "http://localhost/onebilderass/js/froala/save.php",
      data: {
         title: tit,
         content: cont,
         tags: testt,
         category: cat
       }
  })
  .done (function (data) { console.log ('Gönderildi'); })
  .fail (function () {console.log ('Göderilemedi'); });
});

**Comment by okcoker** [comment]
It works fine here https://jsfiddle.net/okcoker/aqnspdtr/5/

There must be something else going on in your app to cause that error unrelated to this library

**Comment by celalnuriakgun** [comment]
In this case, I have no problem, okay but there is a problem in Ajax. I cannot send a test variable, ajax in to data.

**Comment by okcoker** [comment]
I think instead of `taggle.getContainer()` you want to do `taggle.getTags().values`

**Comment by celalnuriakgun** [comment]
Not in getTags(), but I want getting html. :(

**Comment by celalnuriakgun** [comment]
taggle.getTags().values running. It comes in array but I want html. :(

**Comment by okcoker** [comment]
so then you probably want `taggle.getContainer().innerHTML`

**Comment by celalnuriakgun** [comment]
so thanks bro, this amazing. this running but how editable getting html? :))

**Comment by okcoker** [comment]
That's up to you!
