### ISSUE TITLE
Support disabled state

### ISSUE THREAD

**Issue by adamgruber** [okcoker/taggle.js#97]
Would be nice to have an option to put the taggle into a disabled state where tags are not interactable.

**Comment by okcoker** [comment]
Does #74 work for you?

**Comment by adamgruber** [comment]
Yeah that's how I ended up doing it but it might be nice to just have a global option. Anyway thanks for the quick response.

**Comment by okcoker** [comment]
Hmm, how would you propose it worked? A "disabled" state would just remove/hide the text input and buttons within each tag?

**Comment by adamgruber** [comment]
It wouldn't need to hide or remove things, just make them inaccessible. If I pass `isDisabled: true` as an option then it could add the `disabled` attribute to any inputs/buttons within the component.

**Comment by okcoker** [comment]
Will add
