### ISSUE TITLE
Calculations rounded too early

### ISSUE THREAD

**Issue by superelement** [okcoker/taggle.js#98]
The "_fixInputWidth" function rounds calculations too early resulting in certain cases being 1px too large and forcing the tag to the next line, when it should stay on same line.

**Comment by okcoker** [comment]
@superelement Can you provide a JSFiddle link (or equivalent) example of this?

**Comment by m0n9oose** [comment]
same here. @okcoker could you please take a look at my jsfiddle https://jsfiddle.net/c30Lemuz/

It seems input is wider by 1px and always sits in next line

**Comment by okcoker** [comment]
Thanks for this @m0n9oose. Will check out.

**Comment by okcoker** [comment]
@m0n9oose fixed in version 1.13.0 https://jsfiddle.net/c30Lemuz/2/
